apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=  
  DB_PASSWORD: TnVobWFuQDQ1Ng== 
  DB_NAME: cHJvamVjdDE=    
  DB_HOST: bG9jYWxob3N0     
  DB_PORT: NTQzMi==        
  DB_SSL: ZGlzYWJsZQ==