name: Build, Test, and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: go test ./...

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t nuhman9260/my-ecommerce:latest .

    - name: Run Docker container
      run: |
          docker run -d --name my-ecommerce -p 8080:8080 nuhman9260/my-ecommerce:latest
          # Add any commands to test the running container here
          docker ps # List running containers as a simple check

    - name: Push Docker image
      uses: docker/build-push-action@v2
      with:
          context: .
          push: true
          tags: nuhman9260/my-ecommerce:latest

    - name: Clean up
      run: docker container rm -f test-container

    - name: Log out from Docker Hub
      run: docker logout
