name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: go test ./...

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t nuhman9260/my-ecommerce:latest .

    - name: Run Docker container
      run: |
        docker run -d --name my-ecommerce -p 8080:8080 nuhman9260/my-ecommerce:latest
        # Add any commands to test the running container here
        docker ps # List running containers as a simple check

    - name: Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: nuhman9260/my-ecommerce:latest

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: v1.30.1

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --region us-east-1 --name my-eks-cluster

    - name: Apply Kubernetes secrets
      run: kubectl apply -f k8s/secrets.yaml

    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml

    - name: Clean up
      run: docker container rm -f my-ecommerce

    - name: Log out from Docker Hub
      run: docker logout
